server:
  port: 8080

spring:
  application:
    name: product-registration-api

  datasource:
    url: jdbc:h2:mem:product-registration-db
    driver-class-name: org.h2.Driver
    username: "admin"
    password: "admin"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true